### ISSUE TITLE
Deaths Data automation

### ISSUE THREAD

**Issue by Louiiii** [traffordDataLab/local_covid-19#1]
Hi, Firstly this is an amazing tool you've made and I've made some adaptions for it for work.

I've added some additional code to make the deaths import from ons more automated please see below:

**_library(rvest)
library(stringr)_**

  **_tmp <- tempfile(fileext = ".xlsx")
  ##Takes first xlsx file  
  page <- html("https://www.ons.gov.uk/peoplepopulationandcommunity/healthandsocialcare/causesofdeath/datasets/deathregistrationsandoccurrencesbylocalauthorityandhealthboard")
  ext<-page %>%
    html_nodes("a") %>%       # find all links
    html_attr("href") %>%     # get the url
    str_subset("\\.xlsx") %>% # find those that end in xlsx
    .[[1]]                    # look at the first one
  URL<-paste("https://www.ons.gov.uk",ext,sep="")_**

this would be used in pre-processing.R for row 99-101.  

I hope this helps.

Kind regards,

Louis

**Comment by rcatlord** [comment]
Thanks Louis - this is a great idea. I have adapted your code and incorporated it into the [pre-processing script](https://github.com/traffordDataLab/local_covid-19/tree/master/data/pre-processing.R).
