### ISSUE TITLE
Last 7 days cases/rate

### ISSUE THREAD

**Issue by Louiiii** [traffordDataLab/local_covid-19#2]
<img width="284" alt="7 Days" src="https://user-images.githubusercontent.com/65618401/95979589-c360ca80-0e13-11eb-9cd6-e112360367c9.PNG">

Hello,

I hope you are all well.

Just for clarification is the attached (from app.R) supposed to be -days(7) on line 214?  It seems this would count 8 days as max date is inclusive? 

Thanks in advance,

Kind regards,

Louis

**Comment by rcatlord** [comment]
Good spot, thanks Louis! Proves the value of showing your working ;)
